### ISSUE TITLE
Lists are highlighted incorrectly

### ISSUE THREAD

**Issue by aik099** [SublimeColors/Solarized#39]
When dealing with lists, then:

* only 1st number (e.g. `1.`) is highlighted
* sub-lists numbers are not highlighted at all (e.g. `1.1.`)

![markdownwronghighlight](https://cloud.githubusercontent.com/assets/1277526/5647717/3eaf5c7a-9691-11e4-82ab-d344f4596133.png)

**Comment by braver** [comment]
This is in Markdown right? If I remember correctly it's a limitation of the syntax grammar and cannot be solved in this theme.

**Comment by aik099** [comment]
Yes, this is Markdown. Does Markdown format support this, but Sublime Text implementation is incomplete?

**Comment by braver** [comment]
The markdown syntax definition that ships with Sublime only recognizes the first `1.` as `punctuation.definition.list_item.markdown`. `2.` and onward are simply `meta.paragraph.list.markdown`. It's not possible to highlight list numbers correctly because of this error. I don't know of any way to fix the syntax definition, I believe it's closed source.

There is the [Markdown Extended](https://packagecontrol.io/packages/Markdown%20Extended) package that fixes a lot of things that are broken in Sublime's Markdown implementation. I would expect that one to work a lot better. And there is of course [Atom](http://atom.io) :wink:

**Comment by aik099** [comment]
I'm already using `Markdown Extended`. So no luck then. Thanks.
